language: java
notifications:
  hipchat:
    rooms:
      secure: LYX4r43UKmgXMTCPR8FysEzeSzYGDIWaktMKQ4c8oK/Rgc2YVi7nkr4r1ETOfCc22bIpAlZKqXCMc+VpP59WuEQDG/zOgo/65GutX/FiKaFwgbNNciBqF0yM1tiTXed18hOE206iNhxLxYQIelHAR/59dYpJuc9DvTGdGsrOulU=
deploy:
  provider: releases
  api_key:
    secure: DR1GYj61vlnwWg+JGjpJZVkfeJ82SEznoPhcrxxRIWYXdc+fsxLCcoYrDlQmb8jrHG6hNGKqLalMhOHA2cqjWPD7zHzKobW8Y4latvdZiswAFXVu2oAILI10/bFVztK8j8jTDZsRYZakHxaW8KzAolkkxMlTKJmyNh7OKZW+2Rk=
  file: build/libs/xld-advanced-command-plugin-1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xltv-hpuft-plugin
