language: java
notifications:
  hipchat:
    rooms:
      secure: h6UL7QT1im+YVlroG5a77NbeXAiSvQ7jbB8n7GGCyiU6evtn4Lisos4AM5AxmlK5FUmDzsLjD+zfY5gSO7SZRpsBcUAbsRbAEOjC7K3sAvQBgXGd5LWe/iaw9GjSqp7SU/Gslf5n3mh/c0+Y1j1e2vkfXOM1+SAwH+BbBbHssmJ/8v/pr9OGYSRXUMxTxVMfxjnSzyHLZHWy8axLqvJVn5QxtiuWi6Fc+glW8rQ52YK+/jq/40jGNSOSJGndplejqJNLLGp3HGIBF3Ystzhp1B/xbuQCQ2lu5G9/9pLjzXPpUvJv3V5TFsAhnvF30HkSZKt4IhQrw8IV9iAjAY1DhYW5F3ETlDvts3air0w0/PZ8E/0/8n7p/RonlwHk3TPXbEXip5GX9/dr5ZYdZfd4Yi6WbXoUfbik3KHOULbbmi7QwzZAqKsVZaaw6GzsxB0NTrxzZ71FEykLs2yos5UK6eLwdVpoIjnIyN1SWIPmadoIPocmUgm3LWn3M/n0A5+AYeeaVwKS8gIilh+5OwYHgJV97n7QX0IJrLwy3wFwgBiWwcU1AgkBTcAii9Mh6kaS7TngdYxvhJW2yRnJvC2sPj3C8RBpjBOpK0ulOdCSqdX6FcwTviF2dwXvywQu8rVGSPRQ25uPO7tUJg/mKmec5T+AuvUjh6CwBHpWjj6n/Ho=
deploy:
  provider: releases
  api_key:
    secure: abLP6Czc/bamsd1qojlV6sUyKnkUf+Y5k2/VF49wQqLt4P83IorAAGJc+M0qYaafrd7joEMc+N+O+KUWXUL9cJyTmTeEFTLobV1/kRA6M2mPm8kN/LhHLg5J0JSTthWaLb6KfwwOW13Z0e2sj3zYQ/VS/u4RIX/yupR40vL+fyFjqE9QG0bbqFAM+2RcSiOTJOs/unvOoc/kQ5m0UKKtx4zScPIPSyJgNT+MzwBTyAXacH8UpvYWs0SEy5DI2nXLFZYqlvpE7+C9VQDSg6uIHGkILwfpolZLF3vkrhG5ycHbxXB3l7FDSGHrghNudtxHxpdfCd+trVq0dzfAkkDLb3ugOM5lOb83qv2x4utsOo2+HOakcrjctcUySjJbVAuKhiBdsLYCq6zGrIo5/JngT+B0gHEcU83Wjn3fHZrdsv8qhxk0zuaZDTbQP+GC0YXi4s+W3vGj6IA53thlD0fhgRP6bW8p31kjUZOWE05FTlXqxaZoIQm2JlDk2sRlDOQf7Vm4gcp5THZk8V0Bf64AV4VUgI5AJPZ8nhKJTCtiNzU7bNH7ziaFvR/kshJW6PXHJCPpAq2QaCzZiC6/9YTFq5iX5ztSBjNkviFUcf9lbWAk533wCdobw7nlt52F70E5Ka+mRgzNZS4HmDkrmD8VGtE0jJzgvR45F1Bo84e9o+g=
  file: build/libs/xltv-hpuft-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xltv-hpuft-plugin
